required hook: "" #Se for vazio não requer
required world: "" #Se for vazio não requer
required permission: "" #Se for vazio não requer
weight: 1 #Usado para definir se ela será sobreescrita a outra scoreboard

scoreboard:
  title: "&5&lFEAST PLUGINS"
  lines:
    - "&r"
    - " &fTPS: &a%server_tps%"
    - " &fNome: &a%player_name%"
    - "&r"
    - " &fPing: &a%player_ping%"
    - ' &fUptime: &a%server_uptime%'
    - ""
    - " &dfeastplugins.com"