#
#  ______ _____  ___   _____ _____   _____ _____ ___________ _____
#    |  ___|  ___|/ _ \ /  ___|_   _| /  ___/  __ \  _  | ___ \  ___|
#    | |_  | |__ / /_\ \\ `--.  | |   \ `--.| /  \/ | | | |_/ / |__
#    |  _| |  __||  _  | `--. \ | |    `--. \ |   | | | |    /|  __|
#    | |   | |___| | | |/\__/ / | |   /\__/ / \__/\ \_/ / |\ \| |___
#    \_|   \____/\_| |_/\____/  \_/   \____/ \____/\___/\_| \_\____/

# Permissões:
#  feastscore.admin: Acesso ao /feastscore


scoreboard:

  update time: 1 #Tempo em segundos para cada atualização da scoreboard


